### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by vbalaji39** [kernkonzept/manifest#2]
Hi,
I followed the steps as mentioned in this link  https://github.com/kernkonzept/manifest/wiki/LinuxVM                                                                   
 for running Single VM over hypervisor but I am getting the following error when i ran make E=uvmm qemu
vm1     | VMM[vmbus]: 'vbus' capability not found. Hardware access not possible for VM.
vm1     | VMM[main]: Hello out there.
vm1     | VMM[cons]: WARNING: Cannot set console attributes. Output may not work as expected.
vm1     | VMM: FATAL: ERROR: ARM GIC virtualization does not work without passing the virtual GICC via the vbus
vm1     | VMM[vm]: Device creation for virtual device virtio_uart@20000 failed. Disabling device.
vm1     | VMM[]: virtio_net@10000.l4vmm,virtiocap: capability net is invalid.
vm1     | VMM[vm]: Device creation for virtual device virtio_net@10000 failed. Disabling device.
vm1     | VMM: FATAL: ERROR: ARM GIC virtualization does not work without passing the virtual GICC via the vbus
vm1     | VMM[vm]: Device creation for virtual device interrupt-controller failed. Disabling device.
vm1     | VMM: FATAL: Parsing timer interrupt: Argument out of range
qemu-system-aarch64: terminating on signal 2
Makefile:6: recipe for target 'do-all-make-goals' failed
make: *** [do-all-make-goals] Interrupt

Also I did'nt find this file **virt-arm_virt-64.dtb** in any location instead i found virt-arm_virt.dtb. file.  Kindly help me in solving above issue.

**Comment by jermar** [comment]
Hi, both of these symptoms suggest that you are using an old version of uvmm. The error message:

"VMM: FATAL: ERROR: ARM GIC virtualization does not work without passing the virtual GICC via the vbus"

was removed in Change-Id: Ic7b505d0a07397dccb0ae58f12f2cbb10fc04107 (commit [27442cb](https://github.com/kernkonzept/uvmm/commit/27442cb0256ea57e5fb11746ad2ac3b78cca155b)), i.e. November 2018.

Likewise, uvmm switched to using virt-arm_virt-64.dtb instead of virt-arm_virt.dtb in Change-Id: I9d4b72199e5e61f1c265a0653ab297fa6439ccfd (commit [324f55c](https://github.com/kernkonzept/uvmm/commit/324f55c6668fcc7ff171f134ba1c75fb2adbf04d)).

For the tutorials to work, you must use the up-to-date sources from GitHub.

**Comment by vbalaji39** [comment]
Thank You Very Much. I will check with latest sources.
